# Taken from 'gradle recommendModuleVersions'
[versions]
com-fasterxml-jackson-annotation = '2.20.0' # https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotation
com-fasterxml-jackson-core = '2.20.1' # https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
com-fasterxml-jackson-databind = '2.20.1' # https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
javafx-base = "25.0.1"
javafx-controls = "25.0.1"
javafx-fxml = "25.0.1"
javafx-graphics = "25.0.1"
javafx-media = "25.0.1"
javafx-web = "25.0.1"
lombok = "1.18.42" # https://mvnrepository.com/artifact/org.projectlombok/lombok
me-gosimple-nbvcxz = "1.5.1" # https://github.com/GoSimpleLLC/nbvcxz
org-bouncycastle-provider = "1.83"
org-controlsfx-controls = "11.2.2" # https://mvnrepository.com/artifact/org.controlsfx/controlsfx
org-jetbrains-annotations = "26.0.2-1"
org.json = '20250517' # https://mvnrepository.com/artifact/org.json/json
org-junit-jupiter-api = "6.0.1"
org-junit-jupiter-engine = "6.0.1"
org-junit-platform-commons = "6.0.1"
org-junit-platform-launcher = "6.0.1"
org-opentest4j = "1.3.0"