# Taken from 'gradle recommendModuleVersions'
[versions]
javafx-base = "22.0.1"
javafx-controls = "22.0.1"
javafx-fxml = "22.0.1"
javafx-graphics = "22.0.1"
javafx-media = "22.0.1"
javafx-web = "22.0.1"
lombok = "1.18.32"
me-gosimple-nbvcxz = "1.5.1"
org-bouncycastle-provider = "1.78.1"
org-jetbrains-annotations = "24.1.0"
org-junit-jupiter-api = "5.10.2"
org-junit-platform-launcher = "1.10.2"
org-opentest4j = "1.3.0"